name: Auto Merge

on:
  push:
    branches:
      - revision
 permissions:
  contents: write
jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
        token: ${{ secrets.TOKEN_ACCESSO_GENERICO_ADMIN }}

      - name: Check parameter in index file
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.TOKEN_ACCESSO_GENERICO_ADMIN }}
        run: |
          PARAM=$(grep "const versione = *.*.*" index.html || echo "false")
          echo "Parameter found: $PARAM"
          if [ -n "$PARAM" ]; then
            echo "Merging branch revision"
            git fetch
            git checkout main
            echo "checkout main ok"
            git merge revision -X theirs --allow-unrelated-histories
            git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/MaZap75/privato.git main
          else
            echo "Merge condition not met."
          fi
