name: Auto Merge

on:
  push:
    branches:
      - revision

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check parameter in index file
        run: |
          PARAM=$(grep "const versione = *.*.*" index.html || echo "false")
          echo "Parameter found: $PARAM"
          if [ -n "$PARAM" ]; then
            echo "Merging branch revision"
            git checkout master
            git merge revision
          else
            echo "Merge condition not met."
          fi
