name: Auto Merge

on:
  push:
    branches:
      - revision

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     env:
            REPO_ACCESS_TOKEN: ${{ secrets."token accesso geneico admin" }}
      - name: Check parameter in index file
        run: |
          PARAM=$(grep "const versione = *.*.*" index.html || echo "false")
          echo "Parameter found: $PARAM"
          if [ -n "$PARAM" ]; then
            echo "Merging branch revision"
            git config --global user.name "MaZap75"
            git config --global user.email "mzappulla75@gmail.com"
            
            git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
            git checkout
            git fetch
            git checkout main
            git checkout
            echo "checkout main ok"
            git merge revision -X theirs --allow-unrelated-histories
            git push https://x-access-token:${{ secrets.PAT }}@github.com/MaZap75/privato.git main
          
          else 
            echo "Merge condition not met."
          fi
